import "@fortawesome/fontawesome-svg-core/styles.css";
import "../globals.css";
import Header from "@/components/admin/Header";

export const metadata = {
  title: "Indian Palace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
