import "@fortawesome/fontawesome-svg-core/styles.css";
import "../globals.css";


export const metadata = {
  title: "Indian Palace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
